server:
  port: 8999

eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
              - Path=/api/contact/**
